name: autocomplete_sample
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.2.6 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.5.3
  flutter_google_places: ^0.3.0
  google_api_headers: ^1.6.0
  googlemaps_flutter_webservices: ^1.0.0
  awesome_snackbar_content: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
